/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/send` | `/send`; params?: Router.UnknownInputParams; } | { pathname: `${'/(canteen)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/event_details` | `/event_details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/redeem` | `/redeem`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/send` | `/send`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(canteen)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/event_details` | `/event_details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(student)'}/redeem` | `/redeem`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/verify-otp${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/panel${`?${string}` | `#${string}` | ''}` | `/panel${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/send${`?${string}` | `#${string}` | ''}` | `/send${`?${string}` | `#${string}` | ''}` | `${'/(canteen)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/event_details${`?${string}` | `#${string}` | ''}` | `/event_details${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(student)'}/redeem${`?${string}` | `#${string}` | ''}` | `/redeem${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/panel` | `/panel`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/send` | `/send`; params?: Router.UnknownInputParams; } | { pathname: `${'/(canteen)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/event_details` | `/event_details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(student)'}/redeem` | `/redeem`; params?: Router.UnknownInputParams; };
    }
  }
}
